node_js:
- "0.10"
- "0.12"
- 1
- 2
- 3
- 4
- 5
- 6
- 7
sudo: false
language: node_js
script:
  - npm run lint
  - npm run test-travis
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
